# Generated by Django 6.1 on 2026-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
